dist: xenial
language: python
python:
  # - "2.7"
  # - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  # - "pypy2.7"
  # - "pypy3.5" # incompat with pipenv atm
# command to install dependencies
before_install:
  - pip install -U pip pipenv
install:
  - pipenv install --dev
# command to run tests
script:
  - flake8 print_env/
  - pytest
