name: Default branch checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v3

      - name: Install pipenv
        run: pipx install pipenv

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pipenv'

      - run: pipenv install --dev
      - run: pipenv run flake8 print_env/

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v3

      - name: Install pipenv
        run: pipx install pipenv

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pipenv'

      - run: pipenv install --dev
      - run: pipenv run pytest --cov=print_env

  install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install -e .
      - run: print-env --version

  scan-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: npx @eqworks/scan-env --strict
        env:
          PORTUNUS_TOKEN: test/stub/token

  commit-watch:
    runs-on: ubuntu-latest
    if: contains(github.event_name, 'pull_request') # only run on pull requests
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: npx @eqworks/commit-watch -b ${{ github.event.pull_request.base.sha }} -h ${{ github.event.pull_request.head.sha }} -v
