name: PyPi pre-release

on:
  tags:
    - 'v*b*'  # v1.0.0b1

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pipenv
        run: pipx install pipenv

      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
          cache: 'pipenv'

      - run: python -m setup sdist bdist_wheel

      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
